# Generated by Django 3.0.14 on 2023-02-01 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('summary', models.TextField(max_length=800)),
                ('address', models.CharField(max_length=500)),
                ('phone_number', models.IntegerField()),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('degree', models.CharField(blank=True, max_length=200, null=True)),
                ('degree_year', models.IntegerField(blank=True, null=True)),
                ('degree_institution', models.CharField(blank=True, max_length=200, null=True)),
                ('name_of_profesional', models.CharField(blank=True, max_length=200, null=True)),
                ('profesional_experience_year', models.IntegerField(blank=True, null=True)),
                ('profesional_experience_location', models.CharField(blank=True, max_length=200, null=True)),
                ('profesional_experience', models.CharField(blank=True, max_length=2000, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
