# Generated by Django 4.2 on 2023-05-14 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('summary', models.TextField(max_length=800)),
                ('address', models.CharField(max_length=500)),
                ('phone_number', models.IntegerField()),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('degree', models.CharField(blank=True, max_length=200, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('school', models.CharField(blank=True, max_length=200, null=True)),
                ('name_of_previous_job', models.CharField(blank=True, max_length=200, null=True)),
                ('start_year_of_previous_job', models.IntegerField(blank=True, null=True)),
                ('location_of_previous_job', models.CharField(blank=True, max_length=200, null=True)),
                ('description_of_previous_job', models.TextField(blank=True, max_length=2000, null=True)),
                ('name_of_current_job', models.CharField(blank=True, max_length=200, null=True)),
                ('start_date_of_current_job', models.CharField(blank=True, max_length=10, null=True)),
                ('location_of_current_job', models.CharField(blank=True, max_length=200, null=True)),
                ('description_of_current_job', models.TextField(blank=True, max_length=2000, null=True)),
                ('about', models.TextField(blank=True, max_length=2000, null=True)),
                ('username', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
