# Generated by Django 3.0.14 on 2023-02-03 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalinfo',
            old_name='user',
            new_name='username',
        ),
    ]
