# Generated by Django 3.0.14 on 2023-02-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0002_auto_20230203_2042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalinfo',
            old_name='degree_institution',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='personalinfo',
            old_name='name_of_profesional',
            new_name='name_of_current_profession',
        ),
        migrations.RenameField(
            model_name='personalinfo',
            old_name='profesional_experience_location',
            new_name='name_of_previous_profesion',
        ),
        migrations.RenameField(
            model_name='personalinfo',
            old_name='degree_year',
            new_name='start_year',
        ),
        migrations.RenameField(
            model_name='personalinfo',
            old_name='profesional_experience_year',
            new_name='year',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='profesional_experience',
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='about',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='details',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='school',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='start_date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
