# Generated by Django 3.0.14 on 2023-02-04 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0003_auto_20230204_2014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalinfo',
            old_name='name_of_current_profession',
            new_name='name_of_current_job',
        ),
        migrations.RenameField(
            model_name='personalinfo',
            old_name='name_of_previous_profesion',
            new_name='name_of_previous_job',
        ),
    ]
