# Generated by Django 3.0.14 on 2023-02-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0004_auto_20230204_2016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalinfo',
            old_name='description',
            new_name='description_of_current_job',
        ),
        migrations.RenameField(
            model_name='personalinfo',
            old_name='details',
            new_name='description_of_previous_job',
        ),
        migrations.RenameField(
            model_name='personalinfo',
            old_name='location',
            new_name='location_of_current_job',
        ),
        migrations.RenameField(
            model_name='personalinfo',
            old_name='start_date',
            new_name='start_date_of_current_job',
        ),
        migrations.RenameField(
            model_name='personalinfo',
            old_name='start_year',
            new_name='start_year_of_previous_job',
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='location_of_previous_job',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
